<?php

namespace AppBundle\Repository\Specs;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSpecFilters()
    {
        return $this
            ->createQueryBuilder('property')
            ->leftJoin('property.values', 'value')
            ->addSelect('value')
            ->groupBy('value.property, value.value')
            ->getQuery()
            ->getResult()
        ;
    }
}
