AppBundle\Entity\ProductCategory:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProductCategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255


    lifecycleCallbacks: {  }
